FROM nginx:latest

EXPOSE 4242
EXPOSE 80

RUN apt update && apt install tor -y
RUN apt install ssh -y
RUN useradd -m -d /home/ssh_user -G sudo -s /bin/bash ssh_user
RUN mkdir -p /home/ssh_user/.ssh

COPY authorized_keys /home/ssh_user/.ssh/authorized_keys
RUN chown ssh_user:ssh_user /home/ssh_user/.ssh/authorized_keys
RUN chmod 644 /home/ssh_user/.ssh/authorized_keys
COPY init.sh /
RUN chmod +x /init.sh
COPY index.html /usr/share/nginx/html/index.html
COPY nginx.conf /etc/nginx/nginx.conf
COPY sshd_config /etc/ssh/sshd_config
COPY torrc /etc/tor/torrc




